version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: bankaccounthexaarchi_postgres
    environment:
      POSTGRES_DB: bank_account
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: